default: &base
  adapter: postgresql
  pool: 5
  encoding: utf8
  min_messages: warning
  timeout: 5000
  host: localhost

development:
  <<: *base
  database: shekinah_dev

test:
  <<: *base
  database: shekinah_test

production:
  <<: *base
  database: shekinah_prod
  url:  <%= ENV.fetch("DATABASE_URL", "") %>
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
